services:
    stan:
        build:
            context: service
            dockerfile: Dockerfile
        depends_on:
            - postgres
        networks:
            - default
            - db
        env_file:
            - .env
    postgres:
        image: postgres:16-alpine
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - db
        env_file:
            - .env
    nginx:
        image: nginx:alpine
        ports:
            - 8080:80
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
            - ./ui/dist:/var/www/html:ro
        depends_on:
            - stan
        networks:
            - default
        restart: always

networks:
    default:
    db:
        internal: true
