services:
    stan:
        build:
            context: service
            dockerfile: Dockerfile
        volumes:
            - ./common:/config:ro
        depends_on:
            - postgres
        networks:
            - default
            - db
        env_file:
            - .env
    postgres:
        image: postgres:16-alpine
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - db
        env_file:
            - .env
    nginx:
        build:
            context: ui
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./common:/var/www/common:ro
        depends_on:
            - stan
        networks:
            - default
        restart: always

networks:
    default:
    db:
        internal: true
