name: mypy

on:
  push:
    paths:
      - ".github/workflows/mypy.yml"
      - "service/requirements.txt"
      - "**/*.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: service
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt
          pip install types-beautifulsoup4

      - name: Run mypy
        working-directory: service
        run: |
          python -m mypy . --enable-incomplete-feature=NewGenericSyntax
