name: pylint

on:
  push:
    paths:
      - ".github/workflows/pylint.yml"
      - "service/requirements.txt"
      - "**/*.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: service
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Run pylint
        working-directory: service
        run: |
          python -m pylint *.py */ --rcfile=.pylintrc --recursive=y --disable=fixme
